# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-24 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20181124_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publisher',
            new_name='chuban',
        ),
    ]
